<a href="https://colab.research.google.com/github/ijhnosalt/Linear-Algebra_ChE_2nd-Sem-2021-2022/blob/main/Assignment_3_Matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Linear Algebra for ChE
##Assignment 3 : Matrices

### Objectives
At the end of this activity, you will be able to do the following:
1. Understand matrices and how they relate to linear equations.
2. Perform basic matrix operations.
3. Matrix equations and operations can be programmed and translated using Python.

#Discussion


In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline


##Matrices
One of the fundamentals of modern computing is the use and notation of matrices. Matrices can also be used to represent complex equations or multiple interconnected equations, ranging from 2-dimensional to hundreds of thousands of them.

Assume you have an equation system with X and Y.

$$
X = \left\{
    \begin{array}\
        a + b \\ 
        8a - 20y
    \end{array}
\right. \\
Y = \left\{
    \begin{array}\
        a+b+b \\ 
        6a -4b -c \\
        -2a + 8b +4c
    \end{array}
\right. \\
Z = \left\{
    \begin{array}\
      d-4a+6b-8c \\
      6d-a-4b+c \\ 
      4d-a+6b-4c
    \end{array}
\right. 
  $$


X is a two-parameter system of two equations, as we can see. Y, on the other hand, is a three-equation, three-parameter system. They can be represented as matrices in the following ways:

$$
X=\begin{bmatrix} 2 & 2 \\ 8 & {-20}\end{bmatrix} \\
Y=\begin{bmatrix} 2 & 2 & 2 \\ 6 & -4 & -2 \\ -2 & 8 & 4\end{bmatrix}\\
Z=\begin{bmatrix} 16 & -24 & 26 & -48 \\ 66 & 22 & 44 & 20 \\ 42 & -22 & 30 & -42\end{bmatrix}\\
$$


Assuming you've already learned about matrix representation, types, and operations. From now on, we'll do them in Python.

#Declaring Matrices
We'll use a matrix to represent a system of linear equations, as we did in the previous laboratory activity. The entities or numbers that comprise matrices are referred to as matrix elements. The list/array structure of matrices is formed by arranging and ordering these elements in rows and columns. These elements are indexed in the same way that arrays are, based on their position in relation to their rows and columns. The following equation can be used to represent this. X, on the other hand, is a matrices composed of xi,j elements. The number of rows in the matrix is denoted by i, while the number of columns is denoted by j.
Keep in mind that the size of a matrix is i x j.


$$X=\begin{bmatrix}
a_{(0,0)}&a_{(0,1)}&\dots&a_{(0,j-1)}\\
a_{(1,0)}&a_{(1,1)}&\dots&a_{(1,j-1)}\\
\vdots&\vdots&\ddots&\vdots&\\
a_{(i-1,0)}&a_{(i-1,1)}&\dots&a_{(i-1,j-1)}
\end{bmatrix}
$$


In [2]:
def describe_mat(matrix):
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')


In [3]:
A = np.array([
    [13, 21],
    [31, 11]
])
describe_mat(A)


Matrix:
[[13 21]
 [31 11]]

Shape:	(2, 2)
Rank:	2



In [4]:
G = np.array([
    [12,16,13],
    [32,12,44]
])
describe_mat(G)


Matrix:
[[12 16 13]
 [32 12 44]]

Shape:	(2, 3)
Rank:	2



In [5]:
B = np.array([
    [28, 32],
    [25, 14],
    [11, 21]
])
describe_mat(B)


Matrix:
[[28 32]
 [25 14]
 [11 21]]

Shape:	(3, 2)
Rank:	2



In [6]:
H = np.array([31,12,23,44])
describe_mat(H)


Matrix:
[31 12 23 44]

Shape:	(4,)
Rank:	1



#Categorizing Matrices
Matrixes can be classified in several ways. One could be based on their element values, while the other on their shape. We'll do our best to go through them.

##According to shape


###Row and column matrices
Row and column matrices are frequently used in vector and matrix computations. They can also be used to represent a larger vector space's row and column spaces. A single column or row represents a row or column matrix. As a result, row matrices are 1 X j and column matrices are i x 1.

In [7]:
## Declaring a Row Matrix

rowmatrix1D = np.array([
    2, 6, 4, -8
]) ## this is a 1-D Matrix with a shape of (4), it's not really considered as a row matrix.
row_mat_2D = np.array([
    [2,4,6, -8]
]) ## this is a 2-D Matrix with a shape of (1,4)

describe_mat(rowmatrix1D)
describe_mat(row_mat_2D)


Matrix:
[ 2  6  4 -8]

Shape:	(4,)
Rank:	1

Matrix:
[[ 2  4  6 -8]]

Shape:	(1, 4)
Rank:	2



In [8]:
col_mat = np.array([
    [2],
    [4],
    [10]
]) ## this is a 2-D Matrix with a shape of (3,1)
describe_mat(col_mat)


Matrix:
[[ 2]
 [ 4]
 [10]]

Shape:	(3, 1)
Rank:	2



##Square matrices
Square matrices have the same row and column dimensions. A matrix is said to be square if i=j. We can modify our matrix descriptor function to find square matrices.

In [9]:
def describe_mat(matrix):
    is_square = True if matrix.shape[0] == matrix.shape[1] else False 
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')


In [10]:
square_mat = np.array([
    [2,4,10],
    [6,6,16],
    [12,2,4]
])

non_square_mat = np.array([
    [2,4,10],
    [6,6,16]
])
describe_mat(square_mat)
describe_mat(non_square_mat)


Matrix:
[[ 2  4 10]
 [ 6  6 16]
 [12  2  4]]

Shape:	(3, 3)
Rank:	2
Is Square: True

Matrix:
[[ 2  4 10]
 [ 6  6 16]]

Shape:	(2, 3)
Rank:	2
Is Square: False



##According to element values


###Null Matrix
A Null Matrix is one that contains no elements. It's always a vector or a matrices subspace.

In [11]:
def describe_mat(matrix):
    if matrix.size > 0:
        is_square = True if matrix.shape[0] == matrix.shape[1] else False 
        print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')
    else:
        print('Matrix is Null')


In [12]:
null_mat = np.array([])
describe_mat(null_mat)


Matrix is Null


##Zero Matrix
A zero matrix can be any rectangular matrix, but all of its elements must be 0 in order to be considered.

In [13]:
zero_mat_row = np.zeros((2,4))
zero_mat_sqr = np.zeros((4,4))
zero_mat_rct = np.zeros((6,4))

print(f'Zero Row Matrix: \n{zero_mat_row}')
print(f'Zero Square Matrix: \n{zero_mat_sqr}')
print(f'Zero Rectangular Matrix: \n{zero_mat_rct}')


Zero Row Matrix: 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Zero Square Matrix: 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Zero Rectangular Matrix: 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


##One Matrix
A ones matrix, like a zero matrix, can be any rectangular matrix whose elements are all 1s rather than 0s.

In [14]:
ones_mat_row = np.ones((2,4))
ones_mat_sqr = np.ones((4,4))
ones_mat_rct = np.ones((6,4))

print(f'Ones Row Matrix: \n{ones_mat_row}')
print(f'Ones Square Matrix: \n{ones_mat_sqr}')
print(f'Ones Rectangular Matrix: \n{ones_mat_rct}')


Ones Row Matrix: 
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Ones Square Matrix: 
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Ones Rectangular Matrix: 
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


##Diagonal Matrix
A diagonal matrix is a square matrix that only has values along one of its diagonals.

In [15]:
np.array([
    [4,0,0],
    [0,6,0],
    [0,0,10]
])


array([[ 4,  0,  0],
       [ 0,  6,  0],
       [ 0,  0, 10]])

In [16]:
d = np.diag([4,6,10,14])
#d.shape[0] == d.shape[1]
d


array([[ 4,  0,  0,  0],
       [ 0,  6,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 14]])

##Identity Matrix
An identity matrix is a diagonal matrix with all diagonal values equal to one.

In [17]:
np.identity(15)


array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.

In [18]:
np.eye(6)


array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

##Upper Triangular Matrix
An upper triangular matrix is one that has no values below the diagonal.

In [19]:
np.array([
    [2,4,6,8],
    [0,6,2,-2],
    [0,0,10,4],
    [0,0,0,4]
])


array([[ 2,  4,  6,  8],
       [ 0,  6,  2, -2],
       [ 0,  0, 10,  4],
       [ 0,  0,  0,  4]])

In [20]:
F = np.array([
              [4, -6, 8, -10, 12],
              [4, -6, 8, -10, 12],
              [4, -6, 8, -10, 12],
              [4, -6, 8, -10, 12],
              [4, -6, 8, -10, 12],
])
np.triu(F)


array([[  4,  -6,   8, -10,  12],
       [  0,  -6,   8, -10,  12],
       [  0,   0,   8, -10,  12],
       [  0,   0,   0, -10,  12],
       [  0,   0,   0,   0,  12]])

##Lower Triangular Matrix
There are no values above the diagonal in a lower triangular matrix.

In [21]:
np.array([
    [2,0,0],
    [10,6,0],
    [14,16,10]
])

array([[ 2,  0,  0],
       [10,  6,  0],
       [14, 16, 10]])

#Matrix Algebra

##Addition

In [22]:
X = np.array([
    [2,4],
    [4,6],
    [8,2]
])
Y = np.array([
    [4,4],
    [0,0],
    [2,2]
])
X+Y

array([[ 6,  8],
       [ 4,  6],
       [10,  4]])

In [23]:
4+X ##Broadcasting
# 4*np.ones(A.shape)+A

array([[ 6,  8],
       [ 8, 10],
       [12,  6]])

##Subtraction

In [24]:
X-Y

array([[-2,  0],
       [ 4,  6],
       [ 6,  0]])

In [25]:
6-Y == 6*np.ones(Y.shape)-Y

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

##Element-wise Multiplication

In [26]:
X*Y
np.multiply(X,Y)

array([[ 8, 16],
       [ 0,  0],
       [16,  4]])

In [27]:
4*X

array([[ 8, 16],
       [16, 24],
       [32,  8]])

In [28]:
R = np.array([
    [2,4],
    [4,6],
    [8,2]
])
T = np.array([
    [4,4,4],
    [0,0,0]
])
R@T

array([[ 8,  8,  8],
       [16, 16, 16],
       [32, 32, 32]])

In [29]:
alpha=20**-20
X/(alpha+Y)

array([[5.000000e-01, 1.000000e+00],
       [4.194304e+26, 6.291456e+26],
       [4.000000e+00, 1.000000e+00]])

In [30]:
np.add(X,Y)

array([[ 6,  8],
       [ 4,  6],
       [10,  4]])

#Activity

##Task 1
Create a function named mat_desc() that througouhly describes a matrix, it should:



1.   Displays the shape, size, and rank of the matrix.
2.   Displays whether the matrix is square or non-square.
3.   Displays whether the matrix is an empty matrix.
4.   Displays if the matrix is an identity, ones, or zeros matrix

Use 5 sample matrices in which their shapes are not lower than (3,3). In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.




In [31]:
# mat_desc function

def mat_desc(matrix):
  square = False
  matrix = np.array(matrix)
  print(matrix)
  print('Shape', matrix.shape)
  print('Size', matrix.size)
  print('Rank', np.linalg.matrix_rank(matrix))
  if(matrix.shape[0] == matrix.shape[1]):
    square = True
    print('Square Matrix')
  else: 
    print('Non-Square Matrix')
  if(matrix.shape[0] == 0 and matrix.shape[1] == 0):
    print('Empty Matrix')
  else:
    print('Matrix in not empty')
  iden = np.identity(matrix.shape[0])
  if(square and (iden == matrix).all()):
    print('Identity Matrix')
  else:
    print('Not identity matrix')
  one = np.ones((matrix.shape[0], matrix.shape[1]))
  if(one == matrix).all ():
    print('Ones matrix')
  else:
    print('Not a Ones Matrix')
  zero = np.zeros((matrix.shape[0], matrix.shape[1]))
  if((zero == matrix).all()):
    print('Zero Matrix')
  else:
    print('Non-Zero Matrix')

In [32]:
print('Matrix 1:')
mat_desc([[1,1,1,1],[1,1,1,1],[1,1,1,1],[1,1,1,1],[1,1,1,1]])

Matrix 1:
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
Shape (5, 4)
Size 20
Rank 1
Non-Square Matrix
Matrix in not empty
Not identity matrix
Ones matrix
Non-Zero Matrix


In [33]:
print('Matrix 2:')
mat_desc([[2,4,6,8,10], [1,3,5,7,9], [4,16,18,2,8], [1,9,13,18,7], [6,8,11,5,10]])

Matrix 2:
[[ 2  4  6  8 10]
 [ 1  3  5  7  9]
 [ 4 16 18  2  8]
 [ 1  9 13 18  7]
 [ 6  8 11  5 10]]
Shape (5, 5)
Size 25
Rank 5
Square Matrix
Matrix in not empty
Not identity matrix
Not a Ones Matrix
Non-Zero Matrix


In [34]:
print('Matrix 3:')
mat_desc([[1,0,0,0,0,0], [0,1,0,0,0,0], [0,0,1,0,0,0], [0,0,0,1,0,0,], [0,0,0,0,1,0,],[0,0,0,0,0,1]])

Matrix 3:
[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]
Shape (6, 6)
Size 36
Rank 6
Square Matrix
Matrix in not empty
Identity Matrix
Not a Ones Matrix
Non-Zero Matrix


In [35]:
print('Matrix 4:')
mat_desc([[1,1,1,1],[1,1,1,1],[1,1,1,1],[1,1,1,1], [1,1,1,1], [1,1,1,1,], [1,1,1,1]])

Matrix 4:
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
Shape (7, 4)
Size 28
Rank 1
Non-Square Matrix
Matrix in not empty
Not identity matrix
Ones matrix
Non-Zero Matrix


In [36]:
print('Matrix 5:')
mat_desc([[0,0,0,0], [0, 0, 0,0], [0,0,0,0], [0,0,0,0]])

Matrix 5:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Shape (4, 4)
Size 16
Rank 0
Square Matrix
Matrix in not empty
Not identity matrix
Not a Ones Matrix
Zero Matrix


#Task 2

Create a function named mat_operations() that takes in two matrices a input parameters it should:



1.   Determines if the matrices are viable for operation and returns your own error message if they are not viable.
2.   Returns the sum of the matrices.
3.   Returns the differen of the matrices.
4.   Returns the element-wise multiplication of the matrices.
5.   Returns the element-wise division of the matrices.

Use 5 sample matrices in which their shapes are not lower than (3,3). In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.





In [37]:
def mat_operations(matrix1, matrix2):
    matrix1 = np.array(matrix1)
    matrix2 = np.array(matrix2)
    print('Matrix 1:', matrix1)
    print('Matrix 2:', matrix2)
    if(matrix1.shape != matrix2.shape):
        print('Matrices dimensions are invalid and operations cannot be performed.')
        return
    print('Sum of the  matrices:')
    matrixsum = matrix1 + matrix2
    print(matrixsum)
    print('Difference of the  matrices:')
    matrixdifference = matrix1 - matrix2
    print(matrixdifference)
    print('Element-wise multiplication of the  matrices:')
    matrixproduct = np.multiply(matrix1, matrix2)
    print(matrixproduct)
    print('Element-wise division of the  matrices:')
    matrixdividend = np.divide(matrix1, matrix2)
    print(matrixdividend)


In [38]:
print('sample1:')
mat_operations([[4,6,4], [10,8,14], [8,6,1], [3,7,5,]],[[6,8,10,], [18,14,2,12],[2,4,12,8],[15,7,13,9]])

sample1:
Matrix 1: [[ 4  6  4]
 [10  8 14]
 [ 8  6  1]
 [ 3  7  5]]
Matrix 2: [list([6, 8, 10]) list([18, 14, 2, 12]) list([2, 4, 12, 8])
 list([15, 7, 13, 9])]
Matrices dimensions are invalid and operations cannot be performed.


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  This is separate from the ipykernel package so we can avoid doing imports until


In [39]:
print('sample 2:')
mat_operations([[1, 3, 2,2], [1,1,0,2], [3,0,2,4]], [[1,4,2,3],[0,1,2,5],[2,2,2,3]])

sample 2:
Matrix 1: [[1 3 2 2]
 [1 1 0 2]
 [3 0 2 4]]
Matrix 2: [[1 4 2 3]
 [0 1 2 5]
 [2 2 2 3]]
Sum of the  matrices:
[[2 7 4 5]
 [1 2 2 7]
 [5 2 4 7]]
Difference of the  matrices:
[[ 0 -1  0 -1]
 [ 1  0 -2 -3]
 [ 1 -2  0  1]]
Element-wise multiplication of the  matrices:
[[ 1 12  4  6]
 [ 0  1  0 10]
 [ 6  0  4 12]]
Element-wise division of the  matrices:
[[1.         0.75       1.         0.66666667]
 [       inf 1.         0.         0.4       ]
 [1.5        0.         1.         1.33333333]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:19: RuntimeWarning: divide by zero encountered in true_divide


In [40]:
print('sample 3:')
mat_operations([[6, 15, 3], [9,18,9], [18,3,15], [7,15,12]], [[15,12,6],[9,12,18],[9,6,9],[12,12,15]])

sample 3:
Matrix 1: [[ 6 15  3]
 [ 9 18  9]
 [18  3 15]
 [ 7 15 12]]
Matrix 2: [[15 12  6]
 [ 9 12 18]
 [ 9  6  9]
 [12 12 15]]
Sum of the  matrices:
[[21 27  9]
 [18 30 27]
 [27  9 24]
 [19 27 27]]
Difference of the  matrices:
[[-9  3 -3]
 [ 0  6 -9]
 [ 9 -3  6]
 [-5  3 -3]]
Element-wise multiplication of the  matrices:
[[ 90 180  18]
 [ 81 216 162]
 [162  18 135]
 [ 84 180 180]]
Element-wise division of the  matrices:
[[0.4        1.25       0.5       ]
 [1.         1.5        0.5       ]
 [2.         0.5        1.66666667]
 [0.58333333 1.25       0.8       ]]


In [41]:
print('sample 4:')
mat_operations([[3,1,2,4,1], [6,3,6,4,5], [3,2,10,4,1]], [[3,2,1,3,4],[6,2,3,4,5],[6,1,2,3,1]])

sample 4:
Matrix 1: [[ 3  1  2  4  1]
 [ 6  3  6  4  5]
 [ 3  2 10  4  1]]
Matrix 2: [[3 2 1 3 4]
 [6 2 3 4 5]
 [6 1 2 3 1]]
Sum of the  matrices:
[[ 6  3  3  7  5]
 [12  5  9  8 10]
 [ 9  3 12  7  2]]
Difference of the  matrices:
[[ 0 -1  1  1 -3]
 [ 0  1  3  0  0]
 [-3  1  8  1  0]]
Element-wise multiplication of the  matrices:
[[ 9  2  2 12  4]
 [36  6 18 16 25]
 [18  2 20 12  1]]
Element-wise division of the  matrices:
[[1.         0.5        2.         1.33333333 0.25      ]
 [1.         1.5        2.         1.         1.        ]
 [0.5        2.         5.         1.33333333 1.        ]]


In [42]:
print('sample 5:')
mat_operations([[3,1,2,4,1,10], [2,3,1,4,5,5], [2,3,2,5,1,0], [11,3,5,7,10,5]], [[3,2,3,3,4,4],[6,8,12,4,5,1],[1,4,6,12,4,2], [2,13,5,6,12,6]])

sample 5:
Matrix 1: [[ 3  1  2  4  1 10]
 [ 2  3  1  4  5  5]
 [ 2  3  2  5  1  0]
 [11  3  5  7 10  5]]
Matrix 2: [[ 3  2  3  3  4  4]
 [ 6  8 12  4  5  1]
 [ 1  4  6 12  4  2]
 [ 2 13  5  6 12  6]]
Sum of the  matrices:
[[ 6  3  5  7  5 14]
 [ 8 11 13  8 10  6]
 [ 3  7  8 17  5  2]
 [13 16 10 13 22 11]]
Difference of the  matrices:
[[  0  -1  -1   1  -3   6]
 [ -4  -5 -11   0   0   4]
 [  1  -1  -4  -7  -3  -2]
 [  9 -10   0   1  -2  -1]]
Element-wise multiplication of the  matrices:
[[  9   2   6  12   4  40]
 [ 12  24  12  16  25   5]
 [  2  12  12  60   4   0]
 [ 22  39  25  42 120  30]]
Element-wise division of the  matrices:
[[1.         0.5        0.66666667 1.33333333 0.25       2.5       ]
 [0.33333333 0.375      0.08333333 1.         1.         5.        ]
 [2.         0.75       0.33333333 0.41666667 0.25       0.        ]
 [5.5        0.23076923 1.         1.16666667 0.83333333 0.83333333]]
