<a href="https://colab.research.google.com/github/ijhnosalt/Linear-Algebra_ChE_2nd-Sem-2021-2022/blob/main/Assignment_5_Matrix_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Linear Algebra for ChE

##Objectives
1. Understand the fundamental matrix operations.
2. Use the operations to solve the problem.
3. Apply matrix algebra in engineering solutions. 

In [46]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

#Transposition
Transposition is a fundamental operation in matrix algebra. A matrix is transposed by flipping the values of its elements across its diagonals. The rows and columns of the original matrix will be switched as a result of this. As a result, the transpose of matrix A is denoted as $A^T$. As an example:

:$$
M=\begin{bmatrix} 14 & 6 & 2 & \\ 0 & -4 & 16 & \\ 2 & 10 & 18 & \end{bmatrix}
$$


:$$
M^T=\begin{bmatrix} 14 & 0 & 2 & \\ 6 & -4 & 10 & \\ 2 & 16 & 18 & \end{bmatrix}
$$

In [47]:
A = np.array([
    [14, 6, 2],
    [0, -4, 16],
    [2, 10, 18]
])
A

array([[14,  6,  2],
       [ 0, -4, 16],
       [ 2, 10, 18]])

In [48]:
AT1 = np.transpose(A)
AT1

array([[14,  0,  2],
       [ 6, -4, 10],
       [ 2, 16, 18]])

In [49]:
AT2 = A.T
AT2

array([[14,  0,  2],
       [ 6, -4, 10],
       [ 2, 16, 18]])

In [50]:
np.array_equiv(AT1, AT2)

True

In [51]:
B = np.array([
    [2, 14, 8, 18],
    [10, 4, 0, -10],
    [14, -8, 6, 18]
])
B.shape

(3, 4)

In [52]:
np.transpose(B).shape

(4, 3)

In [53]:
B.T.shape

(4, 3)

To test transposition, try making your own matrix (you can use non-squares).

In [54]:
I= np.array ([
    [2, 13, 21],
    [4, -19, 17],
    [2, 6, 15],
    [22, 3, 12]
])
print('I matrix: \n',I, '\n')
print('Shape: ',I.shape)

I matrix: 
 [[  2  13  21]
 [  4 -19  17]
 [  2   6  15]
 [ 22   3  12]] 

Shape:  (4, 3)


In [55]:
print('Transpose Shape: ',np.transpose(I).shape)

Transpose Shape:  (3, 4)


In [56]:
print('Transpose Shape: ',I.T.shape)

Transpose Shape:  (3, 4)


##Dot Product / Inner product

If you remember the dot product from the previous laboratory activity, we will try to implement the same operation with matrices. In matrix dot product, we will get the sum of vector products by row-column pairs. So if we have two matrices $X$ and $Y$:

$$X = \begin{bmatrix}x_{(0,0)}&x_{(0,1)}\\ x_{(1,0)}&x_{(1,1)}\end{bmatrix}, Y = \begin{bmatrix}y_{(0,0)}&y_{(0,1)}\\ y_{(1,0)}&y_{(1,1)}\end{bmatrix}$$

The dot product is then calculated as:
$$X \cdot Y= \begin{bmatrix} x_{(0,0)}*y_{(0,0)} + x_{(0,1)}*y_{(1,0)} & x_{(0,0)}*y_{(0,1)} + x_{(0,1)}*y_{(1,1)} \\  x_{(1,0)}*y_{(0,0)} + x_{(1,1)}*y_{(1,0)} & x_{(1,0)}*y_{(0,1)} + x_{(1,1)}*y_{(1,1)}
\end{bmatrix}$$

As a result, if we assign values to $X$ and $Y$:
$$X = \begin{bmatrix}1&2\\ 0&1\end{bmatrix}, Y = \begin{bmatrix}-1&0\\ 2&2\end{bmatrix}$$

$$X \cdot Y= \begin{bmatrix} 1*-1 + 2*2 & 1*0 + 2*2 \\  0*-1 + 1*2 & 0*0 + 1*2 \end{bmatrix} = \begin{bmatrix} 3 & 4 \\2 & 2 \end{bmatrix}$$
This could be achieved programmatically using `np.dot()`, `np.matmul()` or the `@` operator.

In [57]:
A = np.array([
    [4,3],
    [5,2]
])
M = np.array([
    [4,3],
    [2,3]
])

In [58]:
P= np.array ([  
    [2,14,16,18,10,12,0],
    [4,10,12,14,16,18,2]
])

In [59]:
np.array_equiv(A,M)

False

In [60]:
np.dot(A,M)

array([[22, 21],
       [24, 21]])

In [61]:
A.dot(M)

array([[22, 21],
       [24, 21]])

In [62]:
A @ M

array([[22, 21],
       [24, 21]])

In [63]:
np.matmul(A,M)

array([[22, 21],
       [24, 21]])

When compared to vector dot products, matrix dot products have additional rules. There are fewer constraints because vector dot products are only one dimension. Because we are now dealing with Rank 2 vectors, we must follow the following rules:

### Rule 1: The inner dimensions of the two matrices in question must be the same. 

So given a matrix $A$ with a shape of $(a,b)$ where $a$ and $b$ are any integers. If we want to do a dot product between $A$ and another matrix $B$, then matrix $B$ should have a shape of $(b,c)$ where $b$ and $c$ are any integers. So for given the following matrices:

$$A = \begin{bmatrix}2&4\\5&-2\\0&1\end{bmatrix}, B = \begin{bmatrix}1&1\\3&3\\-1&-2\end{bmatrix}, C = \begin{bmatrix}0&1&1\\1&1&2\end{bmatrix}$$

So in this case $A$ has a shape of $(3,2)$, $B$ has a shape of $(3,2)$ and $C$ has a shape of $(2,3)$. So the only matrix pairs that is eligible to perform dot product is matrices $A \cdot C$, or $B \cdot C$.  

In [64]:
A = np.array([
    [4, 3],
    [2, 2],
    [3, 4]
])
M = np.array([
    [4,2],
    [3,3],
    [4,-1]
])
P = np.array([
    [2,10,16],
    [4,12,16]
])
print(A.shape)
print(M.shape)
print(P.shape)

(3, 2)
(3, 2)
(2, 3)


In [65]:
A @ P

array([[ 20,  76, 112],
       [ 12,  44,  64],
       [ 22,  78, 112]])

In [66]:
M @ P

array([[16, 64, 96],
       [18, 66, 96],
       [ 4, 28, 48]])

If you look closely, you will notice that the shape of the dot product has changed and it is no longer the same as any of the matrices we used. A dot product's shape is actually derived from the shapes of the matrices used. So recall matrix $A$ with a shape of $(a,b)$ and matrix $B$ with a shape of $(b,c)$, $A \cdot B$ should have a shape $(a,c)$.

In [67]:
A @ M.T

array([[22, 21, 13],
       [12, 12,  6],
       [20, 21,  8]])

In [68]:
A = np.array([
    [2,4,6,8]
])
P = np.array([
    [2,1,8,-2]
])
print(A.shape)
print(P.shape)

(1, 4)
(1, 4)


In [69]:
P.T @ A

array([[  4,   8,  12,  16],
       [  2,   4,   6,   8],
       [ 16,  32,  48,  64],
       [ -4,  -8, -12, -16]])

And you can see that when you try to multiply A and B, it returns a `ValueError` due to a mismatch in matrix shape.

### Rule 2: Dot Product has special properties

Dot products are common in matrix algebra, which means they have several distinct properties that should be considered when formulating solutions:
 1. $A \cdot B \neq B \cdot A$
 2. $A \cdot (B \cdot C) = (A \cdot B) \cdot C$
 3. $A\cdot(B+C) = A\cdot B + A\cdot C$
 4. $(B+C)\cdot A = B\cdot A + C\cdot A$
 5. $A\cdot I = A$
 6. $A\cdot \emptyset = \emptyset$ 

In [70]:
A = np.array([
    [14, 10, 6],
    [6, 8, 14],
    [10, 14, 2]
])
B = np.array([
    [16, 6, 16],
    [10, 12, 18],
    [14, 4, 10]
])
C = np.array([
    [2, 10, 4],
    [4, 12, 16],
    [12, 6, 14]
])

In [71]:
A.dot(np.zeros(A.shape))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [72]:
z_mat = np.zeros(A.shape)
z_mat

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [73]:
a_dot_z = A.dot(np.zeros(A.shape))
a_dot_z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [74]:
np.array_equal(a_dot_z,z_mat)

True

In [75]:
null_mat = np.empty(A.shape, dtype=float)
null = np.array(null_mat,dtype=float)
print(null)
np.allclose(a_dot_z,null)

[[1.e-323 5.e-323 2.e-323]
 [2.e-323 6.e-323 8.e-323]
 [6.e-323 3.e-323 7.e-323]]


True

## Determinant

A determinant is a scalar value that can be calculated from a square matrix. In matrix algebra, the determinant is a fundamental and important value. Although it will not be obvious in this laboratory how it can be used practically, it will be extensively used in subsequent lessons.

The determinant of some matrix $A$ is denoted as $det(A)$ or $|A|$. So let's say $A$ is represented as:
$$A = \begin{bmatrix}a_{(0,0)}&a_{(0,1)}\\a_{(1,0)}&a_{(1,1)}\end{bmatrix}$$
We can compute for the determinant as:
$$|A| = a_{(0,0)}*a_{(1,1)} - a_{(1,0)}*a_{(0,1)}$$
So if we have $A$ as:
$$A = \begin{bmatrix}14&6\\2&18\end{bmatrix}, |A| = 3$$

But you might wonder how about square matrices beyond the shape $(2,2)$? We can approach this problem by using several methods such as co-factor expansion and the minors method. This can be taught in the lecture of the laboratory but we can achieve the strenuous computation of high-dimensional matrices programmatically using Python. We can achieve this by using `np.linalg.det()`.

In [76]:
A = np.array([
    [14, 6],
    [2, 18]
])
np.linalg.det(A)

239.99999999999997

In [77]:
J = np.array([
    [14, 6, 10],
    [2, 18, 16],
    [10, 14, 2]
])
np.linalg.det(J)

-3216.000000000001

In [78]:
## Now other mathematics classes would require you to solve this by hand, 
## and that is great for practicing your memorization and coordination skills 
## but in this class we aim for simplicity and speed so we'll use programming
## but it's completely fine if you want to try to solve this one by hand.
B = np.array([
    [2, 6, 10, 12],
    [0, 6, 2, 6],
    [6, 2, 16, 4],
    [10, 4, 12, 16]
])
np.linalg.det(B)

-3760.0000000000014

## Inverse

Another fundamental operation in matrix algebra is the inverse of a matrix. Determining the inverse of a matrix allows us to determine its solvability and properties as a system of linear equations — we'll go over this in more detail in the nect module. Another application of the inverse matrix is to solve the problem of matrix divisibility. Although element-wise division is possible, dividing the entire concept of matrices is not. Inverse matrices provide a related operation that may be similar to "dividing" matrices.

To find the inverse of a matrix, we must go through several steps. Assume we have a matrix $M$:
$$M = \begin{bmatrix}1&7\\-3&5\end{bmatrix}$$
First, we need to get the determinant of $M$.
$$|M| = (1)(5)-(-3)(7) = 26$$
Next, we need to reform the matrix into the inverse form:
$$M^{-1} = \frac{1}{|M|} \begin{bmatrix} m_{(1,1)} & -m_{(0,1)} \\ -m_{(1,0)} & m_{(0,0)}\end{bmatrix}$$
So that will be:
$$M^{-1} = \frac{1}{26} \begin{bmatrix} 5 & -7 \\ 3 & 1\end{bmatrix} = \begin{bmatrix} \frac{5}{26} & \frac{-7}{26} \\ \frac{3}{26} & \frac{1}{26}\end{bmatrix}$$
For higher-dimension matrices you might need to use co-factors, minors, adjugates, and other reduction techinques. To solve this programmatially we can use `np.linalg.inv()`.

In [79]:
T = np.array([
    [20, -10],
    [16, 12]
])

np.array(T @ np.linalg.inv(T), dtype=int)

array([[1, 0],
       [0, 1]])

In [80]:
T = np.array([
    [20, -10],
    [16, 12]
])
J= np.linalg.inv(T)
J

array([[ 0.03 ,  0.025],
       [-0.04 ,  0.05 ]])

In [81]:
J @ T

array([[ 1.00000000e+00,  8.32667268e-17],
       [-1.11022302e-16,  1.00000000e+00]])

In [82]:
## And now let's test your skills in solving a matrix with high dimensions:
N = np.array([
    [16, 5, 23, 2, 1, 4, 4],
    [1, 49, 1, 3, 6, 1, 3],
    [16, 27, 3, 2, 1, 1, 2],
    [2, 3, 0, 4, 3, 6, 3],
    [3, 2, 1, 4, 7, 23, 6],
    [47, -9, 6, 20, 30, 8, -15],
    [-2, -3, 1, 1, 1, 10, 6],
])
N_inv = np.linalg.inv(N)
np.array(N @ N_inv,dtype=int)

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1]])

To determine whether the matrices you've solved are truly the inverse, we use the dot product property for matrices $M$:
$$M\cdot M^{-1} = I$$

In [83]:
squad = np.array([
    [2.25, 3.25, 1.25],
    [4.2, 2.30, 1.50],
    [1.15, 2.60, 2.50]
])
weights = np.array([
    [0.2, 0.2, 0.6]
])
p_grade = squad @ weights.T
p_grade

array([[1.85],
       [2.2 ],
       [2.25]])

##ACTIVITY

###Task 1
Prove and implement the remaining 6 matrix multiplication properties. You may create your own matrices in which their shapes should not be lower than (3, 3). In your methodology, create individual flowcharts for each property and discuss the property you would then present your proofs or validity of your implementation in the results section by comparing your result to present functions from Numpy.

In [84]:
X = np.array([
    [14, 18, 27],
    [2, 14, -2],
    [14, 26, 22]          
])

Y = np.array([
    [25, 52, 43],
    [6, 82, 16],
    [48, -2, -1]          
])

Z = np.array([
    [42, 45, -28],
    [28, -12, 18],
    [48, 2, 74]          
])

In [85]:
print ("First property: X*Y does not equate to Y*X")
print()
print("Matrix X: \n{}".format(X))
print()
print("Matrix Y: \n{}".format(Y))
print()

a=X@Y
print("X@Y\n\n{}".format(a))
print()
b=Y@X
print("Y@X\n\n{}".format(b))
print()

t = np.array_equiv(a,b)
print("X@Y equates to Y@X? \n")
print(t)

First property: X*Y does not equate to Y*X

Matrix X: 
[[14 18 27]
 [ 2 14 -2]
 [14 26 22]]

Matrix Y: 
[[25 52 43]
 [ 6 82 16]
 [48 -2 -1]]

X@Y

[[1754 2150  863]
 [  38 1256  312]
 [1562 2816  996]]

Y@X

[[1056 2296 1517]
 [ 472 1672  350]
 [ 654  810 1278]]

X@Y equates to Y@X? 

False


In [86]:
print ("Second Property: X@(Y@Z) = (X@Y)@Z")
print()
print("Matrix X: \n{}".format(X))
print()
print("Matrix Y: \n{}".format(Y))
print()
print("Matrix Z: \n{}".format(Z))
print()

a=X@(Y@Z)
print("X@(Y@Z)\n\n{}".format(a))
print()
b=(X@Y)@Z
print("(X@Y)@Z\n\n{}".format(b))
print()

t = np.array_equiv(a,b)
print("X@(Y@Z) = (X@Y)@Z? \n")
print(t)

Second Property: X@(Y@Z) = (X@Y)@Z

Matrix X: 
[[14 18 27]
 [ 2 14 -2]
 [14 26 22]]

Matrix Y: 
[[25 52 43]
 [ 6 82 16]
 [48 -2 -1]]

Matrix Z: 
[[ 42  45 -28]
 [ 28 -12  18]
 [ 48   2  74]]

X@(Y@Z)

[[175292  54856  53450]
 [ 51740 -12738  44632]
 [192260  38490  80656]]

(X@Y)@Z

[[175292  54856  53450]
 [ 51740 -12738  44632]
 [192260  38490  80656]]

X@(Y@Z) = (X@Y)@Z? 

True


In [87]:
print ("Third Property: X@(Y+Z) = X@Y + X@Z")
print()
print("Matrix X: \n{}".format(X))
print()
print("Matrix Y: \n{}".format(Y))
print()
print("Matrix Z: \n{}".format(Z))
print()

a=X@(Y+Z)
print("X@(Y@Z)\n\n{}".format(a))
print()
b=X@Y + X@Z
print("X@Y + X@Z\n\n{}".format(b))
print()

t = np.array_equiv(a,b)
print("X@(Y+Z) = X@Y + X@Z? \n")
print(t)

Third Property: X@(Y+Z) = X@Y + X@Z

Matrix X: 
[[14 18 27]
 [ 2 14 -2]
 [14 26 22]]

Matrix Y: 
[[25 52 43]
 [ 6 82 16]
 [48 -2 -1]]

Matrix Z: 
[[ 42  45 -28]
 [ 28 -12  18]
 [ 48   2  74]]

X@(Y@Z)

[[4142 2618 2793]
 [ 418 1174  360]
 [3934 3178 2700]]

X@Y + X@Z

[[4142 2618 2793]
 [ 418 1174  360]
 [3934 3178 2700]]

X@(Y+Z) = X@Y + X@Z? 

True


In [88]:
print ("Fourth Property: (Y+Z)@X = Y@X + Z@X")
print()
print("Matrix X: \n{}".format(X))
print()
print("Matrix Y: \n{}".format(Y))
print()
print("Matrix Z: \n{}".format(Z))
print()

a=(Y+Z)@X
print("(Y+Z)@X\n\n{}".format(a))
print()
b=Y@X + Z@X
print("Y@X + Z@X\n\n{}".format(b))
print()

t = np.array_equiv(a,b)
print("(Y+Z)@X = Y@X + Z@X? \n")
print(t)

Fourth Property: (Y+Z)@X = Y@X + Z@X

Matrix X: 
[[14 18 27]
 [ 2 14 -2]
 [14 26 22]]

Matrix Y: 
[[25 52 43]
 [ 6 82 16]
 [48 -2 -1]]

Matrix Z: 
[[ 42  45 -28]
 [ 28 -12  18]
 [ 48   2  74]]

(Y+Z)@X

[[1342 2954 1945]
 [1092 2476 1526]
 [2366 3626 4198]]

Y@X + Z@X

[[1342 2954 1945]
 [1092 2476 1526]
 [2366 3626 4198]]

(Y+Z)@X = Y@X + Z@X? 

True


In [89]:
print ("Fifth Property: X@I = X")
print()
I = np.array([
              [1,0,0],
              [0,1,0],
              [0,0,1]
])
print("I: \n{}".format(I))
print()
print("Matrix X: \n{}".format(X))
print()

a=X@I
print("X@I\n\n{}".format(a))
print()
b=X

t = np.array_equiv(a,b)
print("X@I = X? \n")
print(t)

Fifth Property: X@I = X

I: 
[[1 0 0]
 [0 1 0]
 [0 0 1]]

Matrix X: 
[[14 18 27]
 [ 2 14 -2]
 [14 26 22]]

X@I

[[14 18 27]
 [ 2 14 -2]
 [14 26 22]]

X@I = X? 

True


In [90]:
print ("Sixth Property: X@0 = 0")
print()
K = np.array([
              [0,0,0],
              [0,0,0],
              [0,0,0]
])
print("K: \n{}".format(K))
print()
print("Matrix X: \n{}".format(X))
print()

a=X@K
print("X@K\n\n{}".format(a))
print()
b=X

t = np.array_equiv(a,b)
print("X@K has any values other than an array of zeroes? \n")
print(t)

Sixth Property: X@0 = 0

K: 
[[0 0 0]
 [0 0 0]
 [0 0 0]]

Matrix X: 
[[14 18 27]
 [ 2 14 -2]
 [14 26 22]]

X@K

[[0 0 0]
 [0 0 0]
 [0 0 0]]

X@K has any values other than an array of zeroes? 

False
